repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  -   repo: https://github.com/psf/black
      rev: 23.12.1
      hooks:
      -   id: black
          args: [--line-length=100]

  -   repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
      -   id: flake8
